// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyCuaHangHoa_UNETI02_TI17A5HN.Data;

#nullable disable

namespace QuanLyCuaHangHoa_UNETI02_TI17A5HN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009023955_KhoiTaoDatabase")]
    partial class KhoiTaoDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.ChiTietDonHoa", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<bool>("DaChotGia")
                        .HasColumnType("bit");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<int?>("MaMau")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("YeuCauRieng")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaDon");

                    b.HasIndex("MaMau");

                    b.ToTable("ChiTietDonHoas");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.ChiTietMau", b =>
                {
                    b.Property<int>("MaChiTietMau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietMau"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaHoa")
                        .HasColumnType("int");

                    b.Property<int>("MaMau")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTieuChuan")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietMau");

                    b.HasIndex("MaHoa");

                    b.HasIndex("MaMau", "MaHoa")
                        .IsUnique();

                    b.ToTable("ChiTietMaus");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaDon")
                        .IsUnique();

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.DipSuDung", b =>
                {
                    b.Property<int>("MaDip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDip"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenDip")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDip");

                    b.HasIndex("TenDip")
                        .IsUnique();

                    b.ToTable("DipSuDungs");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.DonDatHoa", b =>
                {
                    b.Property<int>("MaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDon"));

                    b.Property<string>("DiaChiGiao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HinhThucNhan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LoiNhan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LyDoPhuPhi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PhiGiaoHang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhuPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("ThoiGianNhanGiao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDon");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DonDatHoas");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.GiaoNhan", b =>
                {
                    b.Property<int>("MaGiaoNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoNhan"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<string>("NguoiGiao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianThucTe")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaGiaoNhan");

                    b.HasIndex("MaDon");

                    b.ToTable("GiaoNhans");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.HoaTuoi", b =>
                {
                    b.Property<int>("MaHoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoa"));

                    b.Property<decimal>("DonGiaThamKhao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaLoaiHoa")
                        .HasColumnType("int");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenHoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaHoa");

                    b.HasIndex("MaLoaiHoa");

                    b.ToTable("HoaTuois");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.LichSuXuLyDon", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<int>("NguoiThucHien")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiCu")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TrangThaiMoi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaDon");

                    b.HasIndex("NguoiThucHien");

                    b.ToTable("LichSuXuLyDons");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.LoaiHoa", b =>
                {
                    b.Property<int>("MaLoaiHoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiHoa"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenLoaiHoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLoaiHoa");

                    b.HasIndex("TenLoaiHoa")
                        .IsUnique();

                    b.ToTable("LoaiHoas");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.MauSanPham", b =>
                {
                    b.Property<int>("MaMau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMau"));

                    b.Property<decimal>("GiaCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KieuSanPham")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaDip")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaMau");

                    b.HasIndex("MaDip");

                    b.ToTable("MauSanPhams");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDon")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiGhiNhan")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDon");

                    b.HasIndex("NguoiGhiNhan");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.ChiTietDonHoa", b =>
                {
                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.DonDatHoa", "DonDatHoa")
                        .WithMany("ChiTietDonHoas")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.MauSanPham", "MauSanPham")
                        .WithMany()
                        .HasForeignKey("MaMau")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonDatHoa");

                    b.Navigation("MauSanPham");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.ChiTietMau", b =>
                {
                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.HoaTuoi", "HoaTuoi")
                        .WithMany("ChiTietMaus")
                        .HasForeignKey("MaHoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.MauSanPham", "MauSanPham")
                        .WithMany("ChiTietMaus")
                        .HasForeignKey("MaMau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaTuoi");

                    b.Navigation("MauSanPham");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.DanhGia", b =>
                {
                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.DonDatHoa", "DonDatHoa")
                        .WithOne("DanhGia")
                        .HasForeignKey("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.DanhGia", "MaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonDatHoa");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.DonDatHoa", b =>
                {
                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("DonDatHoas")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.GiaoNhan", b =>
                {
                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.DonDatHoa", "DonDatHoa")
                        .WithMany("GiaoNhans")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonDatHoa");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.HoaTuoi", b =>
                {
                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.LoaiHoa", "LoaiHoa")
                        .WithMany("HoaTuois")
                        .HasForeignKey("MaLoaiHoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiHoa");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.KhachHang", b =>
                {
                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.KhachHang", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.LichSuXuLyDon", b =>
                {
                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.DonDatHoa", "DonDatHoa")
                        .WithMany("LichSuXuLyDons")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.TaiKhoan", null)
                        .WithMany()
                        .HasForeignKey("NguoiThucHien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonDatHoa");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.MauSanPham", b =>
                {
                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.DipSuDung", "DipSuDung")
                        .WithMany("MauSanPhams")
                        .HasForeignKey("MaDip")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DipSuDung");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.ThanhToan", b =>
                {
                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.DonDatHoa", "DonDatHoa")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.TaiKhoan", null)
                        .WithMany()
                        .HasForeignKey("NguoiGhiNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonDatHoa");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.DipSuDung", b =>
                {
                    b.Navigation("MauSanPhams");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.DonDatHoa", b =>
                {
                    b.Navigation("ChiTietDonHoas");

                    b.Navigation("DanhGia");

                    b.Navigation("GiaoNhans");

                    b.Navigation("LichSuXuLyDons");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.HoaTuoi", b =>
                {
                    b.Navigation("ChiTietMaus");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("DonDatHoas");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.LoaiHoa", b =>
                {
                    b.Navigation("HoaTuois");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.MauSanPham", b =>
                {
                    b.Navigation("ChiTietMaus");
                });

            modelBuilder.Entity("QuanLyCuaHangHoa_UNETI02_TI17A5HN.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");
                });
#pragma warning restore 612, 618
        }
    }
}
